package com.shyblack.cryptosignals.entity.enums;

public enum FuturesLifecycleEventType {
	INTENT_CREATED,
	SUBMITTED,
	ACKNOWLEDGED,
	FILL,
	CANCEL_REQUESTED,
	CANCELLED,
	REJECTED,
	EXPIRED,
	FAILED,
	RECONCILED,
	RISK_BLOCKED,
	POSITION_OPENED,
	POSITION_CLOSED,
	PROTECTION_PLACED,
	PROTECTION_FAILED
}
