import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../../core/theme/app_colors.dart';
import '../../widgets/settings_widgets.dart';

class HelpSupportScreen extends StatelessWidget {
  const HelpSupportScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(title: const Text('Help & Support')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            const SettingsSectionTitle('CONTACT'),
            SettingsCard(
              padding: EdgeInsets.zero,
              child: Column(
                children: [
                  _ContactTile(
                    icon: Icons.email_outlined,
                    title: 'Email Support',
                    subtitle: 'support@shyblack.com',
                    onTap: () async {
                      await Clipboard.setData(const ClipboardData(text: 'support@shyblack.com'));
                      if (context.mounted) {
                        ScaffoldMessenger.of(context).showSnackBar(
                          const SnackBar(content: Text('Email copied to clipboard')),
                        );
                      }
                    },
                  ),
                ],
              ),
            ),
            const SettingsSectionTitle('GETTING STARTED'),
            _FaqSection(
              items: const [
                _FaqItem(
                  question: 'What is ShyBlack Crypto Signals?',
                  answer: 'ShyBlack is an AI-powered crypto trading signal platform that analyzes '
                      'market data and generates BUY/SELL signals based on technical indicators '
                      'and news sentiment.',
                ),
                _FaqItem(
                  question: 'How do I get started?',
                  answer: '1. Create your account and sign in.\n'
                      '2. Review your trading mode (Spot/Futures).\n'
                      '3. Set your risk profile in Settings.\n'
                      '4. Enable signal notifications.\n'
                      '5. Connect your exchange for live trading (optional).',
                ),
                _FaqItem(
                  question: 'What is Paper Trading?',
                  answer: 'Paper Trading lets you practice with virtual funds without risking real money. '
                      'Signals are generated using real market data, but no actual orders are placed. '
                      'This is the default and safest mode for new users.',
                ),
              ],
            ),
            const SettingsSectionTitle('SIGNALS'),
            _FaqSection(
              items: const [
                _FaqItem(
                  question: 'How are signals generated?',
                  answer: 'Signals are generated by our server-side signal engine using multiple technical '
                      'indicators including RSI, MACD, Bollinger Bands, EMA, volume analysis, and '
                      'structural analysis. Each signal receives a confidence score and grade (A-D).',
                ),
                _FaqItem(
                  question: 'What do signal grades mean?',
                  answer: 'A = Highest confidence\nB = High confidence\nC = Moderate confidence\nD = Low confidence\n\n'
                      'Only act on signals matching your risk tolerance.',
                ),
                _FaqItem(
                  question: 'What is the difference between BUY and SELL signals?',
                  answer: 'BUY signals indicate potential entry points based on bullish market conditions. '
                      'SELL signals indicate potential exit points or bearish conditions. '
                      'Always do your own research.',
                ),
              ],
            ),
            const SettingsSectionTitle('EXCHANGE CONNECTION'),
            _FaqSection(
              items: const [
                _FaqItem(
                  question: 'How do I connect my exchange?',
                  answer: 'Go to Settings → Connect Exchange Accounts → Add Exchange. '
                      'Enter your Binance API key and secret. '
                      'We recommend creating Read-Only API keys for safety.',
                ),
                _FaqItem(
                  question: 'Is my API key secure?',
                  answer: 'Yes. All API keys and secrets are encrypted at rest using AES-GCM encryption. '
                      'Your API secret is never returned in API responses or stored in plaintext. '
                      'We recommend using API keys with IP restrictions and read-only permissions.',
                ),
              ],
            ),
            const SettingsSectionTitle('RISK DISCLAIMER'),
            SettingsCard(
              child: const Text(
                'Crypto trading involves substantial risk of loss. '
                'Signals are generated for informational purposes only and should not be '
                'considered financial advice. Always do your own research and only invest '
                'what you can afford to lose.',
                style: TextStyle(color: AppColors.muted, fontSize: 13, height: 1.5),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _ContactTile extends StatelessWidget {
  const _ContactTile({required this.icon, required this.title, required this.subtitle, required this.onTap});
  final IconData icon;
  final String title;
  final String subtitle;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return ListTile(
      dense: true,
      contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
      leading: Icon(icon, color: AppColors.accent, size: 22),
      title: Text(title, style: const TextStyle(color: AppColors.onCard, fontWeight: FontWeight.w600, fontSize: 14)),
      subtitle: Text(subtitle, style: const TextStyle(color: AppColors.accent, fontSize: 13)),
      trailing: const Icon(Icons.copy, color: AppColors.muted, size: 18),
      onTap: onTap,
    );
  }
}

class _FaqSection extends StatelessWidget {
  const _FaqSection({required this.items});
  final List<_FaqItem> items;

  @override
  Widget build(BuildContext context) {
    return SettingsCard(
      padding: EdgeInsets.zero,
      child: Column(
        children: items.map((item) => _FaqTile(item: item)).toList(),
      ),
    );
  }
}

class _FaqItem {
  const _FaqItem({required this.question, required this.answer});
  final String question;
  final String answer;
}

class _FaqTile extends StatefulWidget {
  const _FaqTile({required this.item});
  final _FaqItem item;

  @override
  State<_FaqTile> createState() => _FaqTileState();
}

class _FaqTileState extends State<_FaqTile> {
  bool _expanded = false;

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () => setState(() => _expanded = !_expanded),
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Expanded(
                  child: Text(
                    widget.item.question,
                    style: const TextStyle(color: AppColors.onCard, fontWeight: FontWeight.w600, fontSize: 14),
                  ),
                ),
                Icon(
                  _expanded ? Icons.keyboard_arrow_up : Icons.keyboard_arrow_down,
                  color: AppColors.muted,
                  size: 20,
                ),
              ],
            ),
            if (_expanded) ...[
              const SizedBox(height: 8),
              Text(
                widget.item.answer,
                style: const TextStyle(color: AppColors.muted, fontSize: 13, height: 1.5),
              ),
            ],
          ],
        ),
      ),
    );
  }
}
