import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/theme/app_colors.dart';
import '../../../domain/entities/app_settings.dart';
import '../../providers/settings_controller.dart';
import '../../widgets/settings_widgets.dart';

class SignalPreferencesScreen extends ConsumerWidget {
  const SignalPreferencesScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final asyncSettings = ref.watch(settingsControllerProvider);

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(title: const Text('Signal Preferences')),
      body: asyncSettings.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (e, _) => const Center(child: Text('Could not load settings', style: TextStyle(color: AppColors.muted))),
        data: (settings) => SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SettingsSectionTitle('TRADING PARAMETERS'),
              SettingsCard(
                padding: EdgeInsets.zero,
                child: Column(
                  children: [
                    SettingsNavTile(
                      icon: Icons.swap_horiz,
                      title: 'Trading Mode',
                      subtitle: settings.tradingMode.label,
                      trailing: Text(
                        settings.tradingMode.label,
                        style: const TextStyle(color: AppColors.muted, fontSize: 12),
                      ),
                      onTap: () => _pickMode(context, ref, settings),
                    ),
                    SettingsNavTile(
                      icon: Icons.speed,
                      title: 'Risk Profile',
                      subtitle: _riskDescription(settings.riskProfile),
                      trailing: Text(
                        settings.riskProfile.label,
                        style: const TextStyle(color: AppColors.muted, fontSize: 12),
                      ),
                      onTap: () => _pickRisk(context, ref, settings),
                    ),
                    SettingsNavTile(
                      icon: Icons.calculate_outlined,
                      title: 'Position Sizing',
                      subtitle: 'How position size is calculated',
                      trailing: Text(
                        settings.positionSizingMode.label,
                        style: const TextStyle(color: AppColors.muted, fontSize: 12),
                      ),
                      onTap: () => _pickSizing(context, ref, settings),
                    ),
                  ],
                ),
              ),
              const SettingsSectionTitle('SIGNAL INFORMATION'),
              SettingsCard(
                child: Column(
                  children: [
                    _InfoRow(
                      label: 'Signal Engine',
                      value: 'Spot Scorer (multi-indicator)',
                    ),
                    const SizedBox(height: 10),
                    _InfoRow(
                      label: 'Quote Currency',
                      value: settings.quoteCurrency,
                    ),
                    const SizedBox(height: 10),
                    _InfoRow(
                      label: 'Account Mode',
                      value: settings.tradingAccount.label,
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 8),
              const Padding(
                padding: EdgeInsets.symmetric(horizontal: 4),
                child: Text(
                  'Signal generation uses the risk profile and trading mode above. '
                  'All signals are generated by the server-side signal engine.',
                  style: TextStyle(color: AppColors.muted, fontSize: 12),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  String _riskDescription(RiskProfile risk) => switch (risk) {
        RiskProfile.conservative => '~1% risk per trade',
        RiskProfile.moderate => '~2% risk per trade',
        RiskProfile.aggressive => '~3% risk per trade',
      };

  Future<void> _pickMode(BuildContext context, WidgetRef ref, AppSettings settings) async {
    final next = await showDialog<TradingMode>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: AppColors.card,
        title: const Text('Trading Mode'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: TradingMode.values.map((mode) => ListTile(
            title: Text(mode.label),
            trailing: mode == settings.tradingMode ? const Icon(Icons.check, color: AppColors.accent) : null,
            onTap: () => Navigator.pop(context, mode),
          )).toList(),
        ),
      ),
    );
    if (next == null) return;
    await ref.read(settingsControllerProvider.notifier).setTradingMode(next);
  }

  Future<void> _pickRisk(BuildContext context, WidgetRef ref, AppSettings settings) async {
    final next = await showDialog<RiskProfile>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: AppColors.card,
        title: const Text('Risk Profile'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: RiskProfile.values.map((r) => ListTile(
            title: Text(r.label),
            subtitle: Text(_riskDescription(r), style: const TextStyle(color: AppColors.muted, fontSize: 12)),
            trailing: r == settings.riskProfile ? const Icon(Icons.check, color: AppColors.accent) : null,
            onTap: () => Navigator.pop(context, r),
          )).toList(),
        ),
      ),
    );
    if (next == null) return;
    await ref.read(settingsControllerProvider.notifier).patch(settings.copyWith(riskProfile: next));
  }

  Future<void> _pickSizing(BuildContext context, WidgetRef ref, AppSettings settings) async {
    final next = await showDialog<PositionSizingMode>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: AppColors.card,
        title: const Text('Position Sizing'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: PositionSizingMode.values.map((m) => ListTile(
            title: Text(m.label),
            trailing: m == settings.positionSizingMode ? const Icon(Icons.check, color: AppColors.accent) : null,
            onTap: () => Navigator.pop(context, m),
          )).toList(),
        ),
      ),
    );
    if (next == null) return;
    await ref.read(settingsControllerProvider.notifier).patch(settings.copyWith(positionSizingMode: next));
  }
}

class _InfoRow extends StatelessWidget {
  const _InfoRow({required this.label, required this.value});
  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Text(label, style: const TextStyle(color: AppColors.muted, fontSize: 13)),
        const Spacer(),
        Text(value, style: const TextStyle(color: AppColors.onBackground, fontWeight: FontWeight.w600, fontSize: 13)),
      ],
    );
  }
}
